In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LassoCV, Ridge, RidgeCV
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, LabelEncoder, PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from imblearn.over_sampling import SMOTE

# Data loading

In [2]:
data = pd.read_csv('housing-data.csv')

In [3]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')

In [5]:
data.shape

(20640, 10)

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.7 MB

# Data analyzing

In [7]:
data.ocean_proximity.unique()

<ArrowStringArray>
['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND']
Length: 5, dtype: str

In [8]:
# Ocean proximity ko one-hot encode karna
encoder = OneHotEncoder(handle_unknown= 'ignore', sparse_output= False)
encoder_array = encoder.fit_transform(data[['ocean_proximity']])

In [9]:
encoder_df = pd.DataFrame(encoder_array, columns= encoder.get_feature_names_out(['ocean_proximity']), dtype= int)

In [10]:
data = pd.concat([data.drop(columns=['ocean_proximity']), encoder_df], axis= 1)

In [11]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0,0,0,1,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0,0,0,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0,0,0,1,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0,0,0,1,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0,0,0,1,0

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   longitude                   20640 non-null  float64
 1   latitude                    20640 non-null  float64
 2   housing_median_age          20640 non-null  float64
 3   total_rooms                 20640 non-null  float64
 4   total_bedrooms              20433 non-null  float64
 5   population                  20640 non-null  float64
 6   households                  20640 non-null  float64
 7   median_income               20640 non-null  float64
 8   median_house_value          20640 non-null  float64
 9   ocean_proximity_<1H OCEAN   20640 non-null  int64
 10  ocean_proximity_INLAND      20640 non-null  int64
 11  ocean_proximity_ISLAND      20640 non-null  int64
 12  ocean_proximity_NEAR BAY    20640 non-null  int64
 13  ocean_proximity_NEAR OCEAN  20640 non-null  int64
dtypes: float64(9), int64(5)
memory usage: 2.2 MB

In [13]:
# total_bedrooms has some missing values
data['total_bedrooms'] = data['total_bedrooms'].fillna(data['total_bedrooms'].median())

In [14]:
data['rooms_per_household'] = data['total_rooms'] / data['households']
data['bedrooms_per_room'] = data['total_bedrooms'] / data['total_rooms']
data['population_per_household'] = data['population'] / data['households']

In [15]:
data.corr()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN,rooms_per_household,bedrooms_per_room,population_per_household
longitude,1.000000,-0.924664,-0.108197,0.044568,0.069120,0.099773,0.055310,-0.015176,-0.045967,0.321121,-0.055575,0.009446,-0.474489,0.045509,-0.027540,0.081205,0.002476
latitude,-0.924664,1.000000,0.011173,-0.036100,-0.066484,-0.108785,-0.071035,-0.079809,-0.144160,-0.446969,0.351166,-0.016572,0.358771,-0.160818,0.106389,-0.098619,0.002366
housing_median_age,-0.108197,0.011173,1.000000,-0.361262,-0.319026,-0.296244,-0.302916,-0.119034,0.105623,0.045300,-0.236645,0.017020,0.255172,0.021622,-0.153277,0.135622,0.013191
total_rooms,0.044568,-0.036100,-0.361262,1.000000,0.927058,0.857126,0.918484,0.198050,0.134153,-0.003031,0.025624,-0.007572,-0.023022,-0.009175,0.133798,-0.187381,-0.024581
total_bedrooms,0.069120,-0.066484,-0.319026,0.927058,1.000000,0.873535,0.974366,-0.007617,0.049457,0.017966,-0.006158,-0.004322,-0.019667,0.000557,0.001765,0.071649,-0.028325
population,0.099773,-0.108785,-0.296244,0.857126,0.873535,1.000000,0.907222,0.004834,-0.024650,0.074613,-0.020732,-0.010412,-0.060880,-0.024264,-0.072213,0.010035,0.069863
households,0.055310,-0.071035,-0.302916,0.918484,0.974366,0.907222,1.000000,0.013033,0.065843,0.042435,-0.039402,-0.009077,-0.010093,0.001714,-0.080598,0.034498,-0.027309
median_income,-0.015176,-0.079809,-0.119034,0.198050,-0.007617,0.004834,0.013033,1.000000,0.688075,0.168876,-0.237496,-0.009228,0.056197,0.027344,0.326895,-0.545298,0.018766
median_house_value,-0.045967,-0.144160,0.105623,0.134153,0.049457,-0.024650,0.065843,0.688075,1.000000,0.256617,-0.484859,0.023416,0.160284,0.141862,0.151948,-0.233303,-0.023737
ocean_proximity_<1H OCEAN,0.321121,-0.446969,0.045300,-0.003031,0.017966,0.074613,0.042435,0.168876,0.256617,1.000000,-0.607669,-0.013872,-0.314813,-0.342620,-0.099566,0.064916,-0.001613
ocean_proximity_INLAND,-0.055575,0.351166,-0.236645,0.025624,-0.006158,-0.020732,-0.039402,-0.237496,-0.484859,-0.607669,1.000000,-0.010614,-0.240887,-0.262163,0.151107,-0.095453,0.015252
ocean_proximity_ISLAND,0.009446,-0.016572,0.017020,-0.007572,-0.004322,-0.010412,-0.009077,-0.009228,0.023416,-0.013872,-0.010614,1.000000,-0.005499,-0.005985,0.001432,0.014184,-0.001030
ocean_proximity_NEAR BAY,-0.474489,0.358771,0.255172,-0.023022,-0.019667,-0.060880,-0.010093,0.056197,0.160284,-0.314813,-0.240887,-0.005499,1.000000,-0.135818,-0.029598,0.002004,-0.015325
ocean_proximity_NEAR OCEAN,0.045509,-0.160818,0.021622,-0.009175,0.000557,-0.024264,0.001714,0.027344,0.141862,-0.342620,-0.262163,-0.005985,-0.135818,1.000000,-0.034652,0.033843,-0.004386
rooms_per_household,-0.027540,0.106389,-0.153277,0.133798,0.001765,-0.072213,-0.080598,0.326895,0.151948,-0.099566,0.151107,0.001432,-0.029598,-0.034652,1.000000,-0.370308,-0.004852
bedrooms_per_room,0.081205,-0.098619,0.135622,-0.187381,0.071649,0.010035,0.034498,-0.545298,-0.233303,0.064916,-0.095453,0.014184,0.002004,0.033843,-0.370308,1.000000,0.002601
population_per_household,0.002476,0.002366,0.013191,-0.024581,-0.028325,0.069863,-0.027309,0.018766,-0.023737,-0.001613,0.015252,-0.001030,-0.015325,-0.004386,-0.004852,0.002601,1.000000

In [16]:
# Selecting Features & Target
features_to_use = [
    'longitude', 
    'latitude', 
    'housing_median_age', 
    'median_income', 
    'rooms_per_household', 
    'bedrooms_per_room', 
    'population_per_household', 
    'ocean_proximity_<1H OCEAN', 
    'ocean_proximity_INLAND', 
    'ocean_proximity_ISLAND', 
    'ocean_proximity_NEAR BAY', 
    'ocean_proximity_NEAR OCEAN'
]

X = data[features_to_use]
y = data['median_house_value']

# Separate train and test data

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Scaling Data

In [18]:
scale = StandardScaler()
X_train_scale = scale.fit_transform(X_train)
X_test_scale = scale.transform(X_test)

# Apply LinearRegression model

In [19]:
lr = LinearRegression()

In [20]:
lr.fit(X_train_scale, y_train)

LinearRegression()

In [21]:
y_pred_train_lr = lr.predict(X_train_scale)

In [22]:
pd.DataFrame({'Prediction': y_train, 'Result': y_pred_train_lr}).head()

       Prediction         Result
7061     193800.0  219536.663448
14689    169700.0  184923.304621
17323    259800.0  263942.556339
10056    136100.0   77979.604502
15750    500001.0  241882.682415

In [23]:
mean_squared_error(y_train, y_pred_train_lr)**0.5

70873.5862676106

In [24]:
mean_absolute_error(y_train, y_pred_train_lr)

51477.35131103325

In [25]:
r2_score(y_train, y_pred_train_lr)

0.6250593183155446

In [26]:
y_pred_test_lr = lr.predict(X_test_scale)

In [27]:
r2_score(y_test, y_pred_test_lr)

0.5832173569839317

# Applying RidgeCV model

In [28]:
alphas = [0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
rcv = RidgeCV(alphas= alphas, cv= 5)

In [29]:
rcv.fit(X_train_scale, y_train)

RidgeCV(alphas=[0.01, 0.1, 1.0, 10.0, 100.0, 1000.0], cv=5)

In [30]:
y_pred_train_rcv = rcv.predict(X_train_scale)

In [31]:
pd.DataFrame({'Prediction': y_train, 'Result': y_pred_train_rcv}).head()

       Prediction         Result
7061     193800.0  219726.429054
14689    169700.0  185122.917755
17323    259800.0  263414.086085
10056    136100.0   78735.014356
15750    500001.0  241776.715675

In [32]:
mean_squared_error(y_train, y_pred_train_rcv)**0.5

70874.20658999078

In [33]:
mean_absolute_error(y_train, y_pred_train_rcv)

51465.07810992631

In [34]:
r2_score(y_train, y_pred_train_rcv)

0.6250527549362609

In [35]:
y_pred_test_rcv = rcv.predict(X_test_scale)

In [36]:
r2_score(y_test, y_pred_test_rcv)

0.5835129907818866

In [37]:
rcv.alpha_

np.float64(10.0)

# Applying Lasso model

In [38]:
lcv = LassoCV(cv= 5, random_state= 42)

In [39]:
lcv.fit(X_train_scale, y_train)

LassoCV(cv=5, random_state=42)

In [40]:
y_pred_train_lcv = lcv.predict(X_train_scale)

In [41]:
y_pred_test_lcv = lcv.predict(X_test_scale)

In [42]:
r2_score(y_train, y_pred_train_lcv)

0.6248204286700072

In [43]:
r2_score(y_test, y_pred_test_lcv)

0.5852996853275154

In [44]:
lcv.alpha_

np.float64(226.8723455175072)

In [45]:
pd.DataFrame({'Model': ['LinearRegression', 'RidgeCV', 'LassoCV'],
             'Train R2': [r2_score(y_train, y_pred_train_lr), r2_score(y_train, y_pred_train_rcv), r2_score(y_train, y_pred_train_lcv)],
             'Test R2': [r2_score(y_test, y_pred_test_lr), r2_score(y_test, y_pred_test_rcv), r2_score(y_test, y_pred_test_lcv)]})

              Model  Train R2   Test R2
0  LinearRegression  0.625059  0.583217
1           RidgeCV  0.625053  0.583513
2           LassoCV  0.624820  0.585300

# LassoCV is the best performing model among the three, achieving the highest Test R2 score of ~0.5723 and showing better generalization with reduced overfitting.